title: Mediasmart
email: info@mediasmart.io
url:   https://www.mediasmart.io/
description: >
  Mobile first demand side platform (DSP) - Mobile Advertising

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets
  style: :compressed

defaults:
  - scope:
      path: _posts/*
    values:
      sitemap: false
  - scope:
      path: assets/*
    values:
      sitemap: false
  - scope:
      path: public/
    values:
      sitemap: false

plugins:
  - jekyll-sitemap

# code syntax highlight
highlighter: rouge
