title: Mediasmart
email: info@mediasmart.io
url:   http://mediasmart.io
description: >
  Mobile first demand side platform (DSP) - Mobile Advertising

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets
  style: :compressed

gems:
  - jekyll-sitemap
