- title: Be a generous leader
  caption: Example 1
  url: http://google.com
  subtitle: One that helps others succeed and celebrate their success.
  description: A generous leader leads with example, is kind, compassionate, patient and empowers others, both colleagues and customers. And at mediasmart, we make it our goal is to do as much as we can to help both our teammates and our clients succeed.
  longDescription:
    As generous leaders we care. We look for solutions rather than focusing on the problems, always keeping a positive mindset - even in the face of adversity - and trying to understand both sides in each conflict. We are the first ones to volunteer when we can help, and always encourage our team members, never put them down. We exercise patience and compassion, striving to understand the other’s perspective, whether they are our colleagues or our customers.
    And last, but not least, we recognize the efforts or our team members and not only celebrate team successes, but also appreciate the learnings in case of failures. Everybody makes mistakes, and that is totally fine at mediasmart, because you often learn even more from mistakes than from successes.

- title: Another
  caption: Example 1
  url: http://google.com
  subtitle: Bla bla
  description: Other description
  longDescription:
    As generous leaders we care. We look for solutions rather than focusing on the problems, always keeping a positive mindset - even in the face of adversity - and trying to understand both sides in each conflict. We are the first ones to volunteer when we can help, and always encourage our team members, never put them down. We exercise patience and compassion, striving to understand the other’s perspective, whether they are our colleagues or our customers.
    And last, but not least, we recognize the efforts or our team members and not only celebrate team successes, but also appreciate the learnings in case of failures. Everybody makes mistakes, and that is totally fine at mediasmart, because you often learn even more from mistakes than from successes.
